Add support to add components to footer toolbar
FlowingCode/GridExporterAddon pull request #83
Opened 2023-11-27 19:46 UTC by flang

Close #81

2023-11-27 20:54 UTC, paodb approved these changes
LGTM

2023-11-28 12:26 UTC, javier-godoy requested changes

2023-11-28 12:26 UTC, javier-godoy commented on src/main/java/com/flowingcode/vaadin/addons/gridexporter/FooterToolbarItem.java
> +public class FooterToolbarItem {
Class is not serializable

2023-11-29 13:44 UTC, flang commented on src/main/java/com/flowingcode/vaadin/addons/gridexporter/FooterToolbarItem.java
> +public class FooterToolbarItem {
fixed

2023-11-29 19:48 UTC, javier-godoy approved these changes

2023-12-21 20:15 UTC, merged